### ISSUE TITLE
if PATH contains a space chroot.sh will fail

### ISSUE THREAD

**Issue by fferri** [jsarenik/Mac-Hroot#3]
e.g. my `PATH` contains `/Applications/VMware Fusion.app/Contents/Public` then when doing `sudo ./chroot.sh` I get this output:

```
$ sudo ./chroot.sh
/etc/resolv.conf
/etc/hosts
env: Fusion.app/Contents/Public:otherEntries: No such file or directory
```

**Comment by fferri** [comment]
Solution is to quote `PATH="$PATH"` in line 38 of chroot.sh

**Comment by jsarenik** [comment]
Thank you for reporting! Have a look at b9ef892 and let me know.

Feel free to close this issue if it works for you now.

**Comment by fferri** [comment]
Works fine!  👍
